### ISSUE TITLE
cheat dont work now

### ISSUE THREAD

**Issue by kirosi123** [stanuwu/PixelGun3DPCCheat#11]
the cheat doesn't work because of the file winhttp.dll
The game starts and closes immediately

**Comment by kittylover68** [comment]
yeah pixel gun just closes on it own are u using bepinex too?

**Comment by kirosi123** [comment]
yes, i can fix it? or no?

**Comment by kittylover68** [comment]
idk i am waiting for respond too

**Comment by kirosi123** [comment]
Write to me if you find the answer.

**Comment by kirosi123** [comment]
please

**Comment by 4xlov** [comment]
https://cdn.discordapp.com/attachments/1226143470880555069/1226144310169436211/2024-04-06_14-10-15.mp4?ex=6623b2e0&is=66113de0&hm=a28ef35b1810e081555d17240bb23b234f53f5a1ed7d0574b4f57bb8b107de94&
Try this.

**Comment by kirosi123** [comment]
> https://cdn.discordapp.com/attachments/1226143470880555069/1226144310169436211/2024-04-06_14-10-15.mp4?ex=6623b2e0&is=66113de0&hm=a28ef35b1810e081555d17240bb23b234f53f5a1ed7d0574b4f57bb8b107de94& Попробуйте это.

console dont open

**Comment by manWboolz** [comment]
> > https://cdn.discordapp.com/attachments/1226143470880555069/1226144310169436211/2024-04-06_14-10-15.mp4?ex=6623b2e0&is=66113de0&hm=a28ef35b1810e081555d17240bb23b234f53f5a1ed7d0574b4f57bb8b107de94& Попробуйте это.
> 
> console dont open

just type steam://open/console   without numbers

**Comment by kirosi123** [comment]
> > > https://cdn.discordapp.com/attachments/1226143470880555069/1226144310169436211/2024-04-06_14-10-15.mp4?ex=6623b2e0&is=66113de0&hm=a28ef35b1810e081555d17240bb23b234f53f5a1ed7d0574b4f57bb8b107de94& Попробуйте это.
> > 
> > 
> > Консоль не открывается
> 
> Просто введите steam://open/console без цифр

i see

**Comment by stanuwu** [comment]
doorstop is patched, we are working on a solution
