### ISSUE TITLE
If you can't do it, look at this!

### ISSUE THREAD

**Issue by 4xlov** [stanuwu/PixelGun3DPCCheat#13]
https://cdn.discordapp.com/attachments/1226143470880555069/1226144310169436211/2024-04-06_14-10-15.mp4?ex=6623b2e0&is=66113de0&hm=a28ef35b1810e081555d17240bb23b234f53f5a1ed7d0574b4f57bb8b107de94&

I created an account just to tell everyone about this^^

**Comment by codingliar** [comment]
I think it got deleted. steampipe.akamaized.net/depot/2524891/manifest/8827661414814/5/8456022628582481986 (File Not Found)
if u don't mind, please share this version in a mirror 👍

**Comment by manWboolz** [comment]
it dosen't work for me i did everything like you and it saying me that i must uptade the game .

**Comment by kittylover68** [comment]
yeah it said Depot download failed : error downloading manifest 88276614148814 from alibaba.cdn.steampipe.steamcontent.com/depot/2524891/manifest/88

**Comment by manWboolz** [comment]
> yeah it said Depot download failed : error downloading manifest 88276614148814 from alibaba.cdn.steampipe.steamcontent.com/depot/2524891/manifest/88

no its not that . You just downloaded wrong one this is real: download_depot 2524890 2524891 8827661414881476996

**Comment by kittylover68** [comment]
manWboolz thank u it started to download

**Comment by manWboolz** [comment]
> manWboolz thank u it started to download

tell me if it works for you

**Comment by manWboolz** [comment]
> > manWboolz thank u it started to download
> 
> tell me if it works for you

for me no because it still saying that i must update the game

**Comment by kittylover68** [comment]
manWboolz watchh the video again

**Comment by kittylover68** [comment]
AND GUYS I DO NOT RECCOMEND U TO ACTIVATE THE GEM GENERATOR because the chances u getting banned is so high so idk u can try i mean

**Comment by manWboolz** [comment]
> manWboolz watchh the video again

MAN Idk i did everything like him and says to update

**Comment by manWboolz** [comment]
> manWboolz watchh the video again

i have watched video 10 times

**Comment by kittylover68** [comment]
nah it doesnt worrk even if i open the game there is no online lets just wait till he makes a better one

**Comment by kirosi123** [comment]
> https://cdn.discordapp.com/attachments/1226143470880555069/1226144310169436211/2024-04-06_14-10-15.mp4?ex=6623b2e0&is=66113de0&hm=a28ef35b1810e081555d17240bb23b234f53f5a1ed7d0574b4f57bb8b107de94&
> 
> Я создал аккаунт только для того, чтобы рассказать об этом всем^^

![Pixel Gun 3D PC Edition_2024 04 06-23 37](https://github.com/stanuwu/PixelGun3DPCCheat/assets/166227763/558c4e6a-b91f-4116-ada5-c7196eab8d8e)
what i can do

**Comment by kittylover68** [comment]
u cant do anything u shoul wait until he improves the cheat

**Comment by manWboolz** [comment]
everything works but progress dosnt safe

**Comment by ghost** [comment]
how did u get it to work?

> everything works but progress dosnt safe

**Comment by manWboolz** [comment]
it works but i have older version and i cant play only get gems then rip

**Comment by stanuwu** [comment]
doorstop is patched, we are working on a solution
