### ISSUE TITLE
BEPINEX issue

### ISSUE THREAD

**Issue by 123poopi** [stanuwu/PixelGun3DPCCheat#15]
After extracting bepinex core files game doesnt launch.
Maybe try melon loader?

**Comment by kirosi123** [comment]
the game will not start because of the file winhttp.dll

**Comment by kirosi123** [comment]
and it works with all the main staff

**Comment by sqrxxx** [comment]
> and it works with all the main staff

what should i do cuz without winhttp.dll it doesnt work

**Comment by kittylover68** [comment]
guys be patient he is trying to do the script without any mod loader

**Comment by stanuwu** [comment]
doorstop is patched, we are working on a solution
