### ISSUE TITLE
When injecting,

### ISSUE THREAD

**Issue by J4YD3NLUL** [stanuwu/PixelGun3DPCCheat#16]
This error comes up
![image](https://github.com/stanuwu/PixelGun3DPCCheat/assets/163341958/d86dbae2-ac8b-45c6-b0a3-23f65e6c6fc9)

Injector: Extreme Injector V3

**Comment by ImInTheICU** [comment]
Getting the same problem,
Steam version.
![image](https://github.com/stanuwu/PixelGun3DPCCheat/assets/111275373/a19e6ed8-e600-4bd7-b8b9-7a58bdbb8634)

**Comment by stanuwu** [comment]
cheat is patched, new version coming soon
