### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by gagemilner** [stanuwu/PixelGun3DPCCheat#2]
please add a feature that unlocks ultimatum and a feature to change firerate also something to hide and unhide menu

**Comment by sploingg** [comment]
> please add a feature that unlocks ultimatum and a feature to change firerate also something to hide and unhide menu

yes, heavy on the hide and unhide menu

**Comment by LockBorn1** [comment]
Yeah that’s pretty important for sure a option to unlock any weapon via ID would be fantastic
