### ISSUE TITLE
How to dupe MUCH gems in PG3D

### ISSUE THREAD

**Issue by stupedreal** [stanuwu/PixelGun3DPCCheat#6]
find cheatmodulegemgenerator.cs cland and paste this:

        public override void HandleCheat(Player_move_c t)
        {
            if(!IsEnabled()) return;
            for (int i = 0; i < 1.5; i++) //this is a big hak multipier gems ohh im burp sory
            {
                GameObject gameObject = new GameObject();
                CoinBonus cb = gameObject.AddComponent<CoinBonus>();
                cb.player = t.gameObject;
                cb.field_Private_Player_move_c_0 = t;
                cb.CoinItemUpAudioClip = new AudioClip();
                cb.prop_EnumPublicSealedvaNoCoGe5vCoUnique_0 = EnumPublicSealedvaNoCoGe5vCoUnique.Gem;
                cb.field_Private_EnumPublicSealedvaNoCoGe5vCoUnique_0 = EnumPublicSealedvaNoCoGe5vCoUnique.Gem;
                cb.enabled = true;
                cb.SetPlayer();
                cb.Update();
                cb.Method_Private_Void_0();
            }

**Comment by apockr11111111111111111** [comment]
can u explain
