### ISSUE TITLE
i got a ban 

### ISSUE THREAD

**Issue by ntk7777** [stanuwu/PixelGun3DPCCheat#9]
![Screenshot 2024-04-05 131717](https://github.com/stanuwu/PixelGun3DPCCheat/assets/165972327/7a22e25d-8539-4dba-a88e-0f919325233a)

**Comment by Rutra09** [comment]
what were u doin?

**Comment by sploingg** [comment]
> ![Screenshot 2024-04-05 131717](https://private-user-images.githubusercontent.com/165972327/320086868-7a22e25d-8539-4dba-a88e-0f919325233a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzNDM5NTcsIm5iZiI6MTcxMjM0MzY1NywicGF0aCI6Ii8xNjU5NzIzMjcvMzIwMDg2ODY4LTdhMjJlMjVkLTg1MzktNGRiYS1hODhlLTBmOTE5MzI1MjMzYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNVQxOTAwNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNDJmZTFjZWI0MDc4ZmQ3ZWQzZjgwMmM3MGMxODg2NWFiNmE1YzFhMWQzNjNmYjE2MmVjMjMyZjY4OWE3N2M4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._z-g3MMpsVl0qmjV1BOblAIOWfdnAST6AUZWlmemEHA)

me too

**Comment by Rutra09** [comment]
yea, now me too, any body found out how to reset progress?

**Comment by ntk7777** [comment]
> yea, now me too, any body found out how to reset progress?

I don't know I had to make a new Steam account but it's not a IP ban

**Comment by 0NullBit0** [comment]
trash chair

**Comment by sploingg** [comment]
> > yea, now me too, any body found out how to reset progress?
> 
> I don't know I had to make a new Steam account but it's not a IP ban

thank god at least its not an ip ban
